### ISSUE TITLE
How to save an article

### ISSUE THREAD

**Issue by adgad** [Financial-Times/next-clippings-proxy#9]
**First time user who clips an article from FT.com**

/clipthis?url -> Redirect to Interstital -> Opt in -> GET /clip?uuid=blah&action=optin

if(action===optin) {
    set cookie
}
```
fetch('https://next.ft.com/myft/onsite/save/blah')
.then(() => { res.redirect('https://next.ft.com/__opt-in?redirect=<article>#notificationblah

-> No thanks -> GET /clip?uuid=blah&action=cancel
fetch('https://next.ft.com/myft/onsite/save/blah')
.then(() => { res.redirect('http://www.ft.com')
```

**Return users**

/clipthis?url ->check cookie -> redirect/call /clip?uuid=blah&action=optin
```
fetch('https://next.ft.com/myft/onsite/save/blah')
.then(() => { res.redirect('https://next.ft.com/__opt-in?redirect=<article>#notificationblah

```

**Comment by laurieboyes** [comment]
closed - documentation of early implementation plans, not an issue
